pipeline {
    agent any

    stages {
        stage('batch-commands') {
            steps {
                bat 'dir'
                bat 'ver'
                bat 'cd'
            }
        }
    }
}
